name: charts
description: Flutter real time crypto information and charts.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  web_socket_channel: ^2.1.0
  fl_chart: ^0.41.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
